---
driver:
  provision: true

provisioner:
  name: puppet_apply
  manifests_path: manifests
  manifest: local.pp
  modules_path: modules
  hiera_data_path: data
  hiera_deep_merge: true
  puppet_verbose: true
  puppet_debug: false
  require_chef_for_busser: false
  require_puppet_repo: false
  custom_options: '--show_diff'
  verify_host_key: false

transport:
  name: sftp

busser:
  ruby_bindir: /usr/bin

platforms:
  - name: ubuntu-16.04-vagrant-bastion_host
    driver_plugin: vagrant
    driver:
      vagrantfile_erb: Vagrantfile.erb
      box: ubuntu/xenial64
      box_url: http://atlas.hashicorp.com/ubuntu/boxes/xenial64
      #network:
      #- ['private_network', {ip: '192.168.33.33'}]
      #- ["forwarded_port", {guest: 8080, host: 8080}]
      provisioner:
        require_puppet_repo: true
        puppet_apt_repo: "http://apt.puppetlabs.com/puppetlabs-release-xenial.deb"

suites:
  - name: default
